### ISSUE TITLE
如果 title为空字符串""，会crash

### ISSUE THREAD

**Issue by dinghaoz** [li504799868/FlycoTabLayoutZ#19]
同样的设置 1.1.2不会crash

<img width="563" alt="Screen Shot 2020-07-21 at 5 38 18 PM" src="https://user-images.githubusercontent.com/26001134/88038556-f844e480-cb78-11ea-8d4e-fc0c8abe0a2f.png">

`     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.graphics.Bitmap.createBitmap(Bitmap.java:816)
        at com.flyco.tablayout.utils.ViewUtils.generateViewCacheBitmap(ViewUtils.java:19)
        at com.flyco.tablayout.SlidingScaleTabLayout.generateTitleDmg(SlidingScaleTabLayout.java:473)
        at com.flyco.tablayout.SlidingScaleTabLayout.updateTabStyles(SlidingScaleTabLayout.java:462)
        at com.flyco.tablayout.SlidingScaleTabLayout.notifyDataSetChanged(SlidingScaleTabLayout.java:329)
        at com.flyco.tablayout.SlidingScaleTabLayout.initViewPagerListener(SlidingScaleTabLayout.java:302)
        at com.flyco.tablayout.SlidingScaleTabLayout.setViewPager(SlidingScaleTabLayout.java:255)
        at com.lzp.tablayout.demo.ui.SlidingScaleTabLayoutFragmentActivity.onCreate(SlidingScaleTabLayoutFragmentActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by li504799868** [comment]
之前的版本没有做镜像处理，……你为什么要设置一个空的标题呢

**Comment by dinghaoz** [comment]
tab 的个数不定的，个数从网络获取，如果只有一个，不显示title。产品要求

**Comment by dinghaoz** [comment]
有时server 也会下发一个空字符串

**Comment by li504799868** [comment]
嗯， 我这里只能做一个空指针的检查，具体的显示效果还是得你自己控制。

**Comment by li504799868** [comment]
1.2.4已发布。
