### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by SheepYang1993** [li504799868/FlycoTabLayoutZ#5]
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.widget.TextView.getLayoutParams()' on a null object reference
        at com.flyco.tablayout.SlidingScaleTabLayout.setTabLayoutParams(SlidingScaleTabLayout.java:304)
        at com.flyco.tablayout.SlidingScaleTabLayout.notifyDataSetChanged(SlidingScaleTabLayout.java:295)
        at com.flyco.tablayout.SlidingScaleTabLayout.initViewPagerListener(SlidingScaleTabLayout.java:273)
        at com.flyco.tablayout.SlidingScaleTabLayout.setViewPager(SlidingScaleTabLayout.java:249)

**Comment by SheepYang1993** [comment]
找到原因了，存在相同名称的布局导致错误
